"use client";

import Link from "next/link";
import { useApp } from "@/components/app-provider";
import { Icon } from "@/components/icons";
import { EmptyState, ProductMedia } from "@/components/ui";

export default function CartPage() {
  const { cart, cartTotal, setQuantity, removeFromCart } = useApp();
  if (!cart.length) return <div className="page container"><EmptyState icon="cart" title="Your cart is empty" body="Add a fresh item from a local shop to schedule a pickup." href="/shop" action="Browse items"/></div>;
  return <div className="page container"><header className="page-heading"><span className="eyebrow">YOUR CART</span><h1>Review your pickup order</h1><p>One shop per order keeps collection simple and preparation fresh.</p></header><div className="cart-layout"><section className="cart-lines"><div className="cart-store"><Icon name="shop"/><div><small>PICKUP FROM</small><b>{cart[0].product.storeName}</b></div></div>{cart.map(({ product, quantity }) => <article key={product.id}><ProductMedia src={product.imageUrl} alt={product.name} className="cart-thumb"/><div className="cart-line-copy"><small>{product.category}</small><h2>{product.name}</h2><p><Icon name="clock"/>{product.preparationMinutes ?? 15} min preparation</p><div className="quantity"><button type="button" onClick={() => setQuantity(product.id, quantity - 1)} aria-label="Decrease quantity"><Icon name="minus"/></button><b>{quantity}</b><button type="button" onClick={() => setQuantity(product.id, quantity + 1)} aria-label="Increase quantity"><Icon name="plus"/></button></div></div><div className="line-price"><strong>₹{(product.price * quantity).toLocaleString("en-IN")}</strong><button type="button" onClick={() => removeFromCart(product.id)}><Icon name="trash"/>Remove</button></div></article>)}</section><aside className="summary"><span className="eyebrow">ORDER SUMMARY</span><h2>{cart.reduce((sum, line) => sum + line.quantity, 0)} item{cart.reduce((sum, line) => sum + line.quantity, 0) === 1 ? "" : "s"}</h2><dl><div><dt>Items</dt><dd>₹{cartTotal.toLocaleString("en-IN")}</dd></div><div><dt>Marketplace fee</dt><dd>₹0</dd></div><div><dt>Pickup fee</dt><dd>₹0</dd></div><div className="total"><dt>Total</dt><dd>₹{cartTotal.toLocaleString("en-IN")}</dd></div></dl><Link className="button button-primary full" href="/checkout">Choose pickup time <Icon name="arrow"/></Link><small><Icon name="shop"/>Pickup only. Pay the seller directly.</small></aside></div></div>;
}
