"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { useApp } from "@/components/app-provider";
import { Icon } from "@/components/icons";
import { Brand, EmptyState, LoadingState, PaymentBadge, ProductMedia, StatusBadge } from "@/components/ui";
import type { OrderStage, Product, ProductInput, StoreInput, StoreProfile, SupportTicket } from "@/lib/types";

type Tab = "dashboard" | "orders" | "products" | "payments" | "packing" | "tickets" | "reviews" | "settings";
type IconName = Parameters<typeof Icon>[0]["name"];

const categories = ["Meetha Paan", "Sada Paan", "Flavoured Paan", "Special Paan", "Custom Paan"];
const nextStages: Partial<Record<OrderStage, OrderStage[]>> = {
  "Order placed": ["Confirmed", "Rejected"],
  Confirmed: ["Preparing", "Cancelled"],
  Preparing: ["Ready for pickup", "Cancelled"],
  "Ready for pickup": ["Collected"],
};
const emptyProduct: ProductInput = { name: "", category: "Meetha Paan", description: "", price: 0, stock: 0, preparationMinutes: 15, imageUrl: "" };
const emptyStore: StoreInput = { name: "", description: "", address: "", area: "", city: "Hyderabad", openingTime: "09:00", closingTime: "22:00", isOpen: true, contactNumber: "", imageUrl: "", upiId: "", upiQrImageUrl: "" };
const sellerNav: Array<[Tab, string, IconName]> = [
  ["dashboard", "Dashboard", "dashboard"], ["orders", "Orders", "orders"],
  ["products", "Products & Prices", "leaf"], ["payments", "Payments", "wallet"],
  ["packing", "Packing Queue", "box"], ["tickets", "Tickets", "ticket"],
  ["reviews", "Reviews", "star"], ["settings", "Store Settings", "settings"],
];
const storeToInput = (store: StoreProfile): StoreInput => ({ name: store.name, description: store.description ?? "", address: store.address ?? "", area: store.area ?? "", city: store.city, openingTime: store.openingTime ?? "09:00", closingTime: store.closingTime ?? "22:00", isOpen: store.isOpen, contactNumber: store.contactNumber ?? "", imageUrl: store.imageUrl ?? "", upiId: store.upiId ?? "", upiQrImageUrl: store.upiQrImageUrl ?? "" });

function ProductEditor({ product, onClose }: { product?: Product; onClose: () => void }) {
  const { publishProduct, updateProduct } = useApp();
  const [form, setForm] = useState<ProductInput>(product ? { name: product.name, category: product.category, description: product.description, price: product.price, stock: product.stock, preparationMinutes: product.preparationMinutes ?? 15, imageUrl: product.imageUrl ?? "" } : emptyProduct);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const update = (field: keyof ProductInput, value: string | number) => setForm((current) => ({ ...current, [field]: value }));
  async function submit(event: React.FormEvent) {
    event.preventDefault(); setBusy(true); setMessage("");
    try {
      const clean = { ...form, name: form.name.trim(), description: form.description.trim(), imageUrl: form.imageUrl?.trim() || undefined };
      if (product) await updateProduct(product.id, clean); else await publishProduct(clean);
      onClose();
    } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Could not save product."); }
    setBusy(false);
  }
  return <form className="form two-column product-form" onSubmit={submit}><label>Product name<input required value={form.name} onChange={(event) => update("name", event.target.value)} placeholder="e.g. Sweet Paan"/></label><label>Category<select value={form.category} onChange={(event) => update("category", event.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label className="wide">Description<textarea required rows={4} value={form.description} onChange={(event) => update("description", event.target.value)} placeholder="Ingredients, flavour and what makes it special"/></label><label>Price (₹)<input required min="1" type="number" value={form.price || ""} onChange={(event) => update("price", Number(event.target.value))}/></label><label>Available quantity<input required min="0" type="number" value={form.stock} onChange={(event) => update("stock", Number(event.target.value))}/></label><label>Preparation time (minutes)<input required min="1" type="number" value={form.preparationMinutes} onChange={(event) => update("preparationMinutes", Number(event.target.value))}/></label><label>Image URL (optional)<input type="url" value={form.imageUrl} onChange={(event) => update("imageUrl", event.target.value)} placeholder="https://…"/></label>{message ? <p className="form-error wide" role="alert">{message}</p> : null}<div className="form-actions wide"><button type="button" className="button button-outline" onClick={onClose}>Cancel</button><button className="button button-primary" disabled={busy}>{busy ? "Saving…" : product ? "Save changes" : "Publish product"}<Icon name="arrow"/></button></div></form>;
}

function OrderTable({ limit, stages }: { limit?: number; stages?: OrderStage[] }) {
  const { orders, updateOrderStage, updatePaymentStatus } = useApp();
  const [message, setMessage] = useState("");
  const shown = (stages ? orders.filter((order) => stages.includes(order.stage)) : orders).slice(0, limit ?? orders.length);
  async function move(id: string, stage: OrderStage) { try { await updateOrderStage(id, stage); setMessage(`Order moved to “${stage}”.`); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Could not update order."); } }
  if (!shown.length) return <EmptyState icon="orders" title="No pickup orders here" body="Matching customer pickup orders will appear here in real time."/>;
  return <div className="seller-order-table-wrap">{message ? <p className="form-message" role="status">{message}</p> : null}<div className="seller-order-table"><div className="seller-order-head"><span>Order</span><span>Customer</span><span>Pickup time</span><span>Items</span><span>Payment</span><span>Status</span><span>Action</span></div>{shown.map((order) => <article key={order.id}><div><b>#{order.id.slice(0, 7).toUpperCase()}</b><small>{new Date(order.placedAt).toLocaleDateString("en-IN", { day: "numeric", month: "short" })}</small></div><div><b>{order.customerName}</b><small>{order.customerMobile || "No mobile"}</small></div><div><b>{order.pickupTime}</b><small>{new Date(order.pickupDate + "T12:00:00").toLocaleDateString("en-IN", { weekday: "short", day: "numeric", month: "short" })}</small></div><div><b>{order.items.reduce((sum, line) => sum + line.quantity, 0)} items</b><small>{order.items.map((line) => line.product.name).join(", ")}</small></div><div><PaymentBadge status={order.paymentStatus}/><small>₹{order.total.toLocaleString("en-IN")}</small></div><div><StatusBadge stage={order.stage}/></div><div className="seller-row-actions">{order.paymentMethod === "upi" && order.paymentStatus !== "PAID" ? <button type="button" className="seller-small-action secondary" onClick={() => void updatePaymentStatus(order.id, "PAID")}>Confirm paid</button> : null}{(nextStages[order.stage] || []).map((stage) => <button type="button" key={stage} className={stage === "Rejected" || stage === "Cancelled" ? "seller-small-action danger" : "seller-small-action"} onClick={() => void move(order.id, stage)}>{stage === "Confirmed" ? "Accept" : stage === "Ready for pickup" ? "Mark ready" : stage}</button>)}</div></article>)}</div></div>;
}

function StoreEditor() {
  const { user, stores, saveStore } = useApp();
  const store = stores.find((item) => item.id === user?.id);
  const [form, setForm] = useState<StoreInput>(() => store ? storeToInput(store) : { ...emptyStore, name: user?.storeName || user?.name || "", contactNumber: user?.mobile || "" });
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const update = (field: keyof StoreInput, value: string | boolean) => setForm((current) => ({ ...current, [field]: value }));
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); try { await saveStore(form); setMessage("Store settings saved."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Could not save store."); } setBusy(false); }
  return <form className="form two-column store-form" onSubmit={submit}><label>Shop name<input required value={form.name} onChange={(event) => update("name", event.target.value)}/></label><label>Contact number<input required value={form.contactNumber} onChange={(event) => update("contactNumber", event.target.value)} inputMode="tel"/></label><label>Area<input required value={form.area} onChange={(event) => update("area", event.target.value)} placeholder="e.g. Charminar"/></label><label>City<input required value={form.city} onChange={(event) => update("city", event.target.value)}/></label><label className="wide">Pickup address<textarea required rows={3} value={form.address} onChange={(event) => update("address", event.target.value)}/></label><label>Opening time<input type="time" required value={form.openingTime} onChange={(event) => update("openingTime", event.target.value)}/></label><label>Closing time<input type="time" required value={form.closingTime} onChange={(event) => update("closingTime", event.target.value)}/></label><label className="wide">Shop description<textarea rows={3} value={form.description} onChange={(event) => update("description", event.target.value)}/></label><label>Shop image URL<input type="url" value={form.imageUrl} onChange={(event) => update("imageUrl", event.target.value)}/></label><label className="switch-label form-switch"><input type="checkbox" checked={form.isOpen} onChange={(event) => update("isOpen", event.target.checked)}/>Shop is accepting pickup orders</label>{message ? <p className="form-message wide">{message}</p> : null}<button className="button button-primary wide" disabled={busy}>{busy ? "Saving…" : "Save store settings"}<Icon name="arrow"/></button></form>;
}

function PaymentsView() {
  const { user, stores, saveStore, orders } = useApp();
  const store = stores.find((item) => item.id === user?.id);
  const [upiId, setUpiId] = useState(store?.upiId ?? "");
  const [upiQrImageUrl, setUpiQrImageUrl] = useState(store?.upiQrImageUrl ?? "");
  const [message, setMessage] = useState("");
  const paid = orders.filter((order) => order.paymentStatus === "PAID");
  const received = paid.reduce((sum, order) => sum + order.total, 0);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!store) { setMessage("Save store settings first."); return; } try { await saveStore({ ...storeToInput(store), upiId: upiId.trim(), upiQrImageUrl: upiQrImageUrl.trim() }); setMessage("Direct payment details saved."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Could not save payment details."); } }
  return <div className="seller-payments-grid"><section className="seller-payment-summary"><Icon name="wallet"/><h2>₹{received.toLocaleString("en-IN")}</h2><p>Confirmed direct payments</p><dl><div><dt>Paid orders</dt><dd>{paid.length}</dd></div><div><dt>Pay at pickup</dt><dd>{orders.filter((order) => order.paymentMethod === "pay-at-shop").length}</dd></div><div><dt>UPI pending</dt><dd>{orders.filter((order) => order.paymentStatus === "PENDING").length}</dd></div></dl></section><form className="form panel" onSubmit={submit}><h2>Seller UPI settings</h2><p className="seller-form-copy">Payments go directly to your shop. MeraPaan does not hold customer funds.</p><label>UPI ID<input value={upiId} onChange={(event) => setUpiId(event.target.value)} placeholder="shopname@bank"/></label><label>UPI QR image URL (optional)<input type="url" value={upiQrImageUrl} onChange={(event) => setUpiQrImageUrl(event.target.value)} placeholder="https://…"/></label><p className="payment-note"><Icon name="alert"/>Only mark an order paid after it appears in your own account.</p>{message ? <p className="form-message">{message}</p> : null}<button className="button button-primary">Save payment details</button></form></div>;
}

function TicketsView() {
  const { tickets, resolveTicket } = useApp();
  const [selectedId, setSelectedId] = useState(tickets.find((item) => item.status === "Open")?.id ?? tickets[0]?.id);
  const [reply, setReply] = useState("");
  const [message, setMessage] = useState("");
  const selected = tickets.find((item) => item.id === selectedId) ?? tickets[0];
  async function resolve(ticket: SupportTicket) { try { await resolveTicket(ticket.id, reply); setMessage("Ticket resolved and reply saved."); setReply(""); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Could not resolve ticket."); } }
  if (!tickets.length) return <EmptyState icon="ticket" title="No customer tickets" body="Order questions and pickup issues will appear here."/>;
  return <div className="seller-ticket-layout"><section className="seller-ticket-list">{tickets.map((ticket) => <button type="button" className={selected?.id === ticket.id ? "active" : ""} onClick={() => { setSelectedId(ticket.id); setMessage(""); }} key={ticket.id}><span><b>#{ticket.id.slice(0, 7).toUpperCase()}</b><em>{ticket.status}</em></span><strong>{ticket.issue}</strong><small>{ticket.customerName} · Order #{ticket.orderId.slice(0, 6).toUpperCase()}</small></button>)}</section>{selected ? <aside className="seller-ticket-detail"><header><div><small>ORDER SUPPORT</small><h2>{selected.issue}</h2></div><span>{selected.status}</span></header><dl><div><dt>Customer</dt><dd>{selected.customerName}</dd></div><div><dt>Order</dt><dd>#{selected.orderId.slice(0, 8).toUpperCase()}</dd></div></dl><p>{selected.message}</p>{selected.sellerReply ? <div className="seller-reply"><b>Your reply</b>{selected.sellerReply}</div> : null}{selected.status === "Open" ? <><label>Reply<textarea value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Add a resolution note for the customer"/></label><button type="button" className="button button-primary" onClick={() => void resolve(selected)}>Resolve ticket</button></> : null}{message ? <p className="form-message">{message}</p> : null}</aside> : null}</div>;
}

function ReviewsView() {
  const { reviews } = useApp();
  const average = reviews.length ? reviews.reduce((sum, review) => sum + review.stars, 0) / reviews.length : 0;
  if (!reviews.length) return <EmptyState icon="star" title="No verified reviews yet" body="Customers can review your shop after collecting an order."/>;
  return <div className="seller-review-layout"><section className="seller-rating-overview"><strong>{average.toFixed(1)}</strong><span>{"★".repeat(Math.round(average))}{"☆".repeat(5 - Math.round(average))}</span><p>From {reviews.length} collected pickup {reviews.length === 1 ? "order" : "orders"}</p></section><section className="seller-review-list">{reviews.map((review) => <article key={review.id}><header><div className="seller-review-avatar">{review.customerName.charAt(0).toUpperCase()}</div><div><b>{review.customerName}</b><span>{"★".repeat(review.stars)}{"☆".repeat(5 - review.stars)}</span></div><small>{review.createdAt ? new Date(review.createdAt).toLocaleDateString("en-IN") : "Recent"}</small></header><p>{review.comment}</p><small>Verified order #{review.orderId.slice(0, 7).toUpperCase()}</small></article>)}</section></div>;
}

export default function SellPage() {
  const { user, authReady, sellerProducts, orders, tickets, reviews, deactivateProduct, stores, alertsEnabled, activeAlert, enableAlerts, dismissAlert, signOut } = useApp();
  const [tab, setTab] = useState<Tab>("dashboard");
  const [editing, setEditing] = useState<Product>();
  const [showAdd, setShowAdd] = useState(false);
  const [mobileMore, setMobileMore] = useState(false);
  const store = stores.find((item) => item.id === user?.id);
  const metrics = useMemo(() => ({ newOrders: orders.filter((order) => order.stage === "Order placed").length, preparing: orders.filter((order) => order.stage === "Confirmed" || order.stage === "Preparing").length, ready: orders.filter((order) => order.stage === "Ready for pickup").length, revenue: orders.filter((order) => order.paymentStatus === "PAID" || (order.paymentStatus === "PAY_AT_PICKUP" && order.stage === "Collected")).reduce((sum, order) => sum + order.total, 0) }), [orders]);
  const packingCount = metrics.preparing + metrics.ready;
  const openTickets = tickets.filter((ticket) => ticket.status === "Open").length;
  const counts: Partial<Record<Tab, number>> = { orders: metrics.newOrders, packing: packingCount, tickets: openTickets };
  if (!authReady) return <div className="page container"><LoadingState label="Opening seller dashboard…"/></div>;
  if (!user) return <div className="page container"><section className="seller-invite"><div><h1>Your paan shop,<br/>one command centre.</h1><p>Use a separate seller account to manage products, pickup orders, payments and store operations.</p><div className="seller-invite-actions"><Link className="button button-gold" href="/login?role=seller&next=/sell">Sign in as seller <Icon name="arrow"/></Link><Link className="button seller-register-link" href="/login?role=seller&mode=register&next=/sell">Register seller account</Link></div></div><span><Icon name="shop"/></span></section></div>;
  if (!user.roles.includes("seller")) return <div className="page container"><EmptyState icon="shop" title="Seller account required" body="Customer accounts stay in the shopping interface. Sign out and use a separate seller account to open this dashboard." href="/orders" action="Return to customer orders"/></div>;
  const currentLabel = sellerNav.find(([value]) => value === tab)?.[1] ?? "Dashboard";
  const switchTab = (value: Tab) => { setTab(value); setMobileMore(false); };
  const openProductEditor = () => { setTab("products"); setEditing(undefined); setShowAdd(true); };

  return <div className="seller-app"><aside className="seller-portal-sidebar"><Link href="/sell" className="seller-portal-brand"><Brand/><small>Seller portal</small></Link><nav aria-label="Seller navigation">{sellerNav.map(([value, label, icon]) => <button type="button" className={tab === value ? "active" : ""} onClick={() => switchTab(value)} key={value}><Icon name={icon}/><span>{label}</span>{counts[value] ? <em>{counts[value]}</em> : null}</button>)}</nav><div className="seller-portal-note"><Icon name="leaf"/><span>Paan connects people<br/>Hyderabad tastes better</span></div></aside><div className="seller-workspace"><header className="seller-topbar"><div className="seller-store-status"><span><Icon name="shop"/></span><div><b>{store?.name || user.storeName || user.name}</b><small>{store?.area ? `${store.area}, ` : ""}{store?.city || "Hyderabad"}</small></div></div><div className={store?.isOpen === false ? "seller-open-state closed" : "seller-open-state"}><i/><span><b>{store?.isOpen === false ? "Closed for orders" : "Open for pickup"}</b><small>Scheduled pickup orders</small></span></div><div className="seller-top-actions"><button type="button" className={alertsEnabled ? "seller-alert-toggle enabled" : "seller-alert-toggle"} onClick={enableAlerts}><Icon name="volume"/>{alertsEnabled ? "Alerts enabled" : "Enable alerts"}</button><div className="seller-avatar">{user.name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase()}</div><button type="button" className="seller-signout" onClick={() => void signOut()}><Icon name="logout"/>Sign out</button></div></header><main className="seller-portal-main"><header className="seller-page-title"><div><h1>{tab === "dashboard" ? "Seller dashboard" : currentLabel}</h1><p>{tab === "dashboard" ? "Here’s what’s happening with your pickup operations today." : tab === "orders" ? "Accept requests and keep every customer updated." : tab === "products" ? "Add real products and keep prices, stock and preparation time accurate." : tab === "payments" ? "Confirm direct payments and manage your shop UPI details." : tab === "packing" ? "Prepare accepted orders in pickup-time order." : tab === "tickets" ? "Resolve customer questions connected to real orders." : tab === "reviews" ? "See feedback from verified collected orders." : "Manage pickup location, hours and shop visibility."}</p></div>{tab === "dashboard" || tab === "products" ? <button type="button" className="button button-gold seller-add-product" onClick={openProductEditor}><Icon name="plus"/>Add product</button> : null}</header>
    {tab === "dashboard" ? <Dashboard metrics={metrics} sellerProducts={sellerProducts} tickets={tickets} reviews={reviews} openTickets={openTickets} switchTab={switchTab}/> : null}
    {tab === "orders" ? <OrderTable/> : null}{tab === "packing" ? <OrderTable stages={["Confirmed", "Preparing", "Ready for pickup"]}/> : null}
    {tab === "products" ? <section>{showAdd || editing ? <div className="editor-panel"><header><h2>{editing ? `Edit ${editing.name}` : "Add a real product"}</h2><button type="button" aria-label="Close editor" onClick={() => { setShowAdd(false); setEditing(undefined); }}><Icon name="close"/></button></header><ProductEditor product={editing} onClose={() => { setShowAdd(false); setEditing(undefined); }}/></div> : null}{sellerProducts.length ? <div className="seller-product-list">{sellerProducts.map((product) => <article key={product.id}><ProductMedia src={product.imageUrl} alt={product.name}/><div><span className={product.status === "published" ? "shop-state" : "shop-state closed"}>{product.status}</span><h3>{product.name}</h3><p>{product.category} · {product.preparationMinutes ?? 15} min</p></div><strong>₹{product.price}</strong><span>{product.stock} in stock</span><div><button type="button" onClick={() => { setShowAdd(false); setEditing(product); }}><Icon name="edit"/>Edit</button>{product.status !== "draft" ? <button type="button" className="danger-text" onClick={() => { if (window.confirm(`Deactivate ${product.name}?`)) void deactivateProduct(product.id); }}><Icon name="trash"/>Deactivate</button> : null}</div></article>)}</div> : <EmptyState icon="leaf" title="No products yet" body="Add your first real product when it is available for pickup."/>}</section> : null}
    {tab === "payments" ? <PaymentsView key={store ? store.id + store.upiId : "payments"}/> : null}{tab === "tickets" ? <TicketsView/> : null}{tab === "reviews" ? <ReviewsView/> : null}{tab === "settings" ? <StoreEditor key={store ? store.id + store.name + store.area : "settings"}/> : null}
  </main></div>{activeAlert?.audience === "seller" ? <div className="order-alert-toast seller-order-alert" role="status" aria-live="assertive"><Icon name="volume"/><div><b>{activeAlert.title}</b><span>{activeAlert.body}</span></div><button type="button" onClick={dismissAlert} aria-label="Dismiss alert"><Icon name="close"/></button></div> : null}<SellerMobileNav tab={tab} counts={counts} mobileMore={mobileMore} setMobileMore={setMobileMore} switchTab={switchTab}/></div>;
}

function Dashboard({ metrics, sellerProducts, tickets, reviews, openTickets, switchTab }: { metrics: { newOrders: number; preparing: number; ready: number; revenue: number }; sellerProducts: Product[]; tickets: SupportTicket[]; reviews: ReturnType<typeof useApp>["reviews"]; openTickets: number; switchTab: (tab: Tab) => void }) {
  const lowStock = sellerProducts.filter((product) => product.stock < 5);
  return <><div className="seller-metrics"><button type="button" onClick={() => switchTab("orders")}><span><Icon name="orders"/></span><div><small>New orders</small><strong>{metrics.newOrders}</strong><em>Needs your response</em></div></button><button type="button" onClick={() => switchTab("packing")}><span><Icon name="clock"/></span><div><small>Preparing</small><strong>{metrics.preparing}</strong><em>Being made now</em></div></button><button type="button" onClick={() => switchTab("packing")}><span><Icon name="box"/></span><div><small>Ready for pickup</small><strong>{metrics.ready}</strong><em>Awaiting customer</em></div></button><button type="button" onClick={() => switchTab("payments")}><span><Icon name="rupee"/></span><div><small>Order value</small><strong>₹{metrics.revenue.toLocaleString("en-IN")}</strong><em>Collected or paid</em></div></button></div><div className="seller-dashboard-grid"><section className="seller-dashboard-panel pickup-panel"><header><h2>Pickup queue</h2><button type="button" onClick={() => switchTab("orders")}>View all orders<Icon name="arrow"/></button></header><OrderTable limit={5} stages={["Order placed", "Confirmed", "Preparing", "Ready for pickup"]}/></section><aside className="seller-dashboard-panel attention-panel"><header><h2>Needs attention</h2><span>{lowStock.length + openTickets}</span></header><h3>Low stock items</h3>{lowStock.slice(0, 4).map((product) => <button type="button" key={product.id} onClick={() => switchTab("products")}><Icon name="box"/><span><b>{product.name}</b><small>{product.stock === 0 ? "Out of stock" : `Only ${product.stock} left`}</small></span><Icon name="chevron"/></button>)}{!lowStock.length ? <p>Inventory is healthy.</p> : null}<h3>Open tickets</h3>{tickets.filter((ticket) => ticket.status === "Open").slice(0, 3).map((ticket) => <button type="button" key={ticket.id} onClick={() => switchTab("tickets")}><Icon name="ticket"/><span><b>{ticket.issue}</b><small>{ticket.customerName}</small></span><Icon name="chevron"/></button>)}{!openTickets ? <p>No tickets need attention.</p> : null}</aside></div><div className="seller-lower-grid"><section className="seller-dashboard-panel seller-mini-summary"><header><h2>Payments summary</h2><button type="button" onClick={() => switchTab("payments")}>View payments<Icon name="arrow"/></button></header><strong>₹{metrics.revenue.toLocaleString("en-IN")}</strong><span>Confirmed order value</span></section><section className="seller-dashboard-panel seller-recent-reviews"><header><h2>Recent reviews</h2><button type="button" onClick={() => switchTab("reviews")}>View reviews<Icon name="arrow"/></button></header>{reviews.slice(0, 2).map((review) => <div key={review.id}><b>{review.customerName}</b><span>{"★".repeat(review.stars)}{"☆".repeat(5 - review.stars)}</span><p>{review.comment}</p></div>)}{!reviews.length ? <p>No verified reviews yet.</p> : null}</section></div></>;
}

function SellerMobileNav({ tab, counts, mobileMore, setMobileMore, switchTab }: { tab: Tab; counts: Partial<Record<Tab, number>>; mobileMore: boolean; setMobileMore: (open: boolean) => void; switchTab: (tab: Tab) => void }) {
  const primary: Array<[Tab, string, IconName]> = [["dashboard", "Dashboard", "dashboard"], ["orders", "Orders", "orders"], ["packing", "Packing", "box"], ["products", "Products", "leaf"]];
  return <><nav className="seller-mobile-nav" aria-label="Seller mobile navigation">{primary.map(([value, label, icon]) => <button type="button" className={tab === value ? "active" : ""} onClick={() => switchTab(value)} key={value}><Icon name={icon}/><span>{label}</span>{counts[value] ? <em>{counts[value]}</em> : null}</button>)}<button type="button" className={["payments", "tickets", "reviews", "settings"].includes(tab) ? "active" : ""} onClick={() => setMobileMore(!mobileMore)}><Icon name="more"/><span>More</span></button></nav>{mobileMore ? <div className="seller-mobile-more">{sellerNav.filter(([value]) => ["payments", "tickets", "reviews", "settings"].includes(value)).map(([value, label, icon]) => <button type="button" onClick={() => switchTab(value)} key={value}><Icon name={icon}/>{label}{counts[value] ? <em>{counts[value]}</em> : null}</button>)}</div> : null}</>;
}
